### ISSUE TITLE
pawn issue with moving to end of board

### ISSUE THREAD

**Issue by BenCos17** [WildStriker/WildCogs#11]
thanks for creating this cog 
However when I was using it I noticed that the pawn when it gets to the end of the board can't be moved to the last sqaure to get a promotion and instead just errors out 
I have attached a screenshot 
![image](https://user-images.githubusercontent.com/52817096/183757417-39dd48af-9ce1-4e52-985b-94abe856d266.png)
![image](https://user-images.githubusercontent.com/52817096/183757544-f2fdf97d-6715-4f86-8e90-573ebcf09c51.png)

**Comment by WildStriker** [comment]
Hi @BenCos17,

Technically this is an invalid move because you must explicitly notate what piece you are promoting to as per [Standard Algebraic notation](https://en.wikipedia.org/wiki/Algebraic_notation_(chess)#Pawn_promotion)

e.g. instead of passing `e8` you should be passing `e8Q` to promote to a queen (R, B, N are options as well)

The [error message](https://github.com/WildStriker/WildCogs/blob/e44e44e9d764f886861451af6460a4356e812dc7/chessgame/commands/player.py#L119) isn't particularly helpful but that is due to the limitation of how the information is relayed back from [python-chess](https://github.com/niklasf/python-chess)

`python-chess`, the engine that this cog wraps around appears to have a more [helpful error message](https://github.com/niklasf/python-chess/blob/3b412c53504efa4e36a75e13755244d8c3f4bd85/chess/__init__.py#L3019) that will state you must include the promotion type.. but it appears to be a bit verbose as I think it prints the whole board too using FEN


When I have a chance I'll see if this can be improved a bit for this situation:
 - I can either pass the `python-chess` error message out in full and that might give enough information for the issue and hopefully not be to overwhelming to most users
 - Or I can try to see if the error message is specific to promotion and send a friendlier message to the end user
   - If I go this route another one to look out for ambiguous moves (two pieces of the same type that can move to the same location)
   - all other errors will just have a generic message as before

**Comment by BenCos17** [comment]
Thanks
