### ISSUE TITLE
Cog request | Chess Game

### ISSUE THREAD

**Issue by SHADOW6** [WildStriker/WildCogs#4]
In your cog Chessgame 
Would you beable to add a couple functions?
The ability to resume a game. After typing the game name, the bot would post the board in a new post.
The ability close a game.
The ability to resign from a game.
A server based score board for W:# | L:#  for all players and top 10
and lastly a way to manage this score board should you wish to reset it or modify it if a user is cheating.

I am still trying to find you on discord to no avil, Id like to compensate you if you could made these addons happen for me.
Thanks in advance!

**Comment by WildStriker** [comment]
Hey @SHADOW6 ,

Thanks for your suggestions I can start working on some of these in my spare time.  Should be fairly easy to implement!

There is already an ability to have draws so the score board should probably also include total draws as well. W:# | L:# | D:#

As for closing the game that can be useful but probably could end up being used instead of draws (when drawing by agreement).
  * Perhaps if less than 5 - 10 moves are made then the players have the ability to agree to wipe the game and it will not count as a draw. This can be helpful if:
    * If a game was created just for testing purposes
    * or accidentally creating games
    * etc
  *  This could also be managed by the bot owner can force quit any game at any time at their discretion.

**Comment by AAA3A-AAA3A** [comment]
Hello,
I am now using this cog for my redbot and it is great!
It was difficult to understand how to move a part with the command though.
Have any of the improvements you mentioned been implemented?
Thanks in advance.

**Comment by WildStriker** [comment]
Hey @AAA3A-AAA3A,

No I have not implemented any of these changes yet.

I'll look into adding some of these features a bit at a time.

I know I was stuck a bit on making some major changes on how I stored the game data sessions, but this will break compatibility with the way it is currently being handled. I.E. all unfinished games can not completed if I push these changes and you will likely need to clear out the cogs data or roll back to a previous version of this cog to complete the games and update again.  I might need to think about how to handle this to make it some what user friendly or just let things break :disappointed:

As for difficulty understanding on how to move a part, are you referring to understanding the chess notation?

Perhaps there can be a help menu that will list some notation to help people get started but you may wish to search for "chess notation" as there may be better help online.  starting at this wiki may help:
https://en.wikipedia.org/wiki/Algebraic_notation_(chess)

essentially you want to move all your pieces by first adding the letter of that piece followed by the position on the board.

- Pawns are the exception to the rule, no letter is needed just the next position
- Rook = R
- Knight = N
- Bishop = B
- Queen = Q
- King = K

For castling there is special notation

- O-O (kingside castling)
- O-O-O (queenside castling)

If you prefer, or when its ambiguous you can also move pieces by just putting the two board positions of the piece:

- `!chess move game_name b1c3` instead of `!chess move game_name Nc3` to move the white knight piece

**Comment by AAA3A-AAA3A** [comment]
Hello,
Following my message of the other time, I learned a little bit the syntax of the cogs of the redbot, I am thus writing a code to allow the owner of the bot to close a game when he wishes it with a confirmation. Only one problem. In the code below, only the games in the current channel are taken into account, how to get all the open games in the server?
`        try:
            games = await self._get_games(ctx.channel)
            game = games[game_name]
        except KeyError:
            embed.add_field(name="Game does not exist",
                            value="This game doesn't appear to exist, please check the "
                            "game list to ensure you are entering it correctly.")
            await ctx.send(embed=embed)
            return`
Thanks in advance and have a nice day.

**Comment by AAA3A-AAA3A** [comment]
Since I didn't get an answer, I continued to search. I just realized that it was perhaps possible to have several parts of the same name by grouping the channels. So I'm going to ask for the id of a textual lounge.

**Comment by WildStriker** [comment]
Hello,

Update for this issue.  I managed to work through some new features.

- You can now use `[p]chess show <game_name>` to repost a game.
- There is now a scoreboard!
    - scoreboard will not update for games played against yourself
    - I decided to implement an elo rating system as well
        - all players will start at 1200 elo, and based on other players rank will increase / decrease as they play
        - though doesn't have a "matchmaking" purpose players could find it useful to track their progress in server / find players with matching skill level
    - you can list all player's scores (10 at a time with a menu to scroll through)
        - can be sorted on elo, wins, losses, or ties. Default is total wins
    - find a specific player's score by name / id
    - bot owner can clear the scoreboard entitely for the server, or target a specific player
    - the bot owner can also use the `[p]chess scoreboard increment` command to increase / decrease (with negative numbers) the players elo, wins, losses, and ties on the scoreboard as well

Changes have been pushed through.  Closing this issue
