### ISSUE TITLE
You can start a chess game with bots

### ISSUE THREAD

**Issue by Skyridr** [WildStriker/WildCogs#5]
Apparently you can start a chess game against bots. Maybe best to prevent that :).

**Comment by WildStriker** [comment]
Hi Skyridr,

Yes this can be problematic, specially if the bot isn't able to play :smile:

I pushed some changes that requires the other player to accept a new game.  This seems like a better option in case someone mistakenly starts a game with someone they do not want to play with, or the other player does not wish to play.

The other play will need to respond by clicking on a check mark (:heavy_check_mark:) or x (:x:) emoji, and it will time out after 10 minutes with no response.

**Comment by Skyridr** [comment]
Thanks! Some really nice chances, appreciate it!

Would be nice as well if admins can close/quit any game. But maybe i should create a new ticket for that 🙂

**Comment by Skyridr** [comment]
Btw. Just tested it, and it appears you can still target bots. Is that intended? Even if it requests the bot to accept the game. Not sure if it's more "valid" so to speak that if target is a bot, decline request completely.

**Comment by WildStriker** [comment]
Only reason I left that in is just in case someone may want to add some kind of bot in the future that would have the ability to play a game.  It is probably completely unrealistic and if you think it is more of a nuisance I can always prevent it as you originally requested and if that turns out it is needed, someone can let me know and I will deal with it then.

As it is now since the bot can't accept, nor decline it will default / timeout and somewhat has the same result.

As for the admin quitting / creating games I think that would fall under some of the requested items for issue #4 so no need to create another issue.

**Comment by AAA3A-AAA3A** [comment]
@Skyridr I made a PR with a new feature so that the bot owner can close any game. There is even the possibility to run the command in another channel than the one where the game is running with the "channel" argument. Since I have time, do you want me to work on a user-definable feature to prevent or not bots from playing?

**Comment by Skyridr** [comment]
Sweet! Having the ability for bots to play would be a nice optional addition. Especially if you are bored and no one is around.

**Comment by AAA3A-AAA3A** [comment]
You did not understand what I said. I just wanted to include a setting to prevent games from starting with bots. Since the developer decided to keep the feature for now, I suggested including a parameter that can be adjusted by the bot owner.

**Comment by Skyridr** [comment]
Sorry, was at work and when you mentioned:

> do you want me to work on a user-definable feature to prevent or not bots from playing

I assumed you meant the ability for bots to play.

But ya. Seeing bots are unable to play. I personally (and that's me) don't see any value to have the ability to invite bots.

**Comment by AAA3A-AAA3A** [comment]
I suggested that you prevent game launches with bots. Since expand it was not secure, I can put a parameter for it.

**Comment by WildStriker** [comment]
Noted, to provide a better user experience let's remove the ability to start a game with a bot.

If this causes problems I will revisit... maybe in the future this cog could have some AI controlled chess bot :laughing:
- I'll have to do some research on this but I think python-chess can integrate with stockfish
  - https://python-chess.readthedocs.io/en/latest/engine.html
- or I might be able to use something like this https://pypi.org/project/stockfish/

**Comment by AAA3A-AAA3A** [comment]
I made a code that displays a message when trying to start a game with a bot. The functionality can even be deactivated by the owner of the bot.

**Comment by AAA3A-AAA3A** [comment]
I do a PR as soon as the other is merged so as not to mix everything up and have the right variables.

**Comment by AAA3A-AAA3A** [comment]
![image](https://user-images.githubusercontent.com/89632044/139251655-86c4a778-30f1-4491-a272-644c68836ccb.png)

**Comment by AAA3A-AAA3A** [comment]
I did a PR to correct this problem. You can close this problem.
